site_name: Poly Hammer Docs
site_dir: site

nav:
  - Home: index.md
<<<<<<< Updated upstream
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
=======
  - Hammer Build Tool:
    - Setup: hammer-build-tool/setup.md
    - Create Releases: hammer-build-tool/create-releases.md
  - Meta-Human DNA Addon: '!include ./meta-human-dna-addon/mkdocs.yml'
>>>>>>> Stashed changes

theme:
  name: material
  custom_dir: "overrides"
  logo: assets/polyhammer.svg
  favicon: assets/images/favicon.ico
  features:
    - content.code.copy
    - navigation.footer
    - search.suggest

  font:
    text: Roboto
    code: Roboto Mono

  palette:
    - scheme: polyhammer-dark
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: polyhammer-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  analytics:
    provider: google
    property: !ENV GA_ID

  social:
    - icon: simple/x
      link: https://x.com/PolyHammerTools
    - icon: simple/linkedin
      link: https://www.linkedin.com/company/poly-hammer
    - icon: simple/github
      link: https://github.com/poly-hammer
    - icon: simple/youtube
      link: https://www.youtube.com/channel/UCBJMFeZQpXmsfR__Ep8Uxow

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - sane_lists
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tasklist
  - pymdownx.magiclink
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.arithmatex
