site_name: Poly Hammer
site_dir: site
repo_url: "https://github.com/poly-hammer/poly-hammer-docs"

nav:
  - Home: index.md
  - Hammer Build Tool:
    - Setup: hammer-build-tool/setup.md
    - Create Releases: hammer-build-tool/create-releases.md
  # BEGIN EXTERNAL DOCS
  - Character DNA Addon:
    - Quick Start: meta-human-dna-addon/index.md
    - Terminology: meta-human-dna-addon/terminology.md
    - Helpful Resources: meta-human-dna-addon/helpful-resources.md
    - Unreal Configuration: meta-human-dna-addon/unreal-configuration.md
    - Textures: meta-human-dna-addon/textures.md
    - User Interface:
      - Import: meta-human-dna-addon/user-interface/import.md
      - Face Board: meta-human-dna-addon/user-interface/face-board.md
      - Utilities: meta-human-dna-addon/user-interface/utilities.md
      - View Options: meta-human-dna-addon/user-interface/view-options.md
      - Rig Logic: meta-human-dna-addon/user-interface/rig-logic.md
      - Shape Keys: meta-human-dna-addon/user-interface/shape-keys.md
      - Output: meta-human-dna-addon/user-interface/output.md
    - Workflows:
      - Face Form Wrap: meta-human-dna-addon/workflows/face-form-wrap.md
    - Contributing:
      - Development: meta-human-dna-addon/contributing/development.md
      - Documentation: meta-human-dna-addon/contributing/documentation.md
      - Testing: meta-human-dna-addon/contributing/testing.md
  # END EXTERNAL DOCS

theme:
  name: shadcn
  custom_dir: overrides
  icon: assets/polyhammer.svg
  favicon: assets/favicon.ico
  show_title: true
  topbar_sections: false
  katex_options: {}
  pygments_style:
    light: shadcn-light
    dark: github-dark

plugins:
  - search

extra:
  analytics:
    id: !ENV GA_ID

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.magiclink
